version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook
    hostname: docker.w261
    privileged: true
    user: root
    environment:
      - NB_USER=ec2-user
      - CHOWN_HOME=yes
      - GRANT_SUDO=yes
      - NB_UID=500
      - NB_GID=500
    command: bash -c "start.sh jupyter lab --LabApp.token='' --LabApp.authenticate_prometheus=False --LabApp.port=8889"
    ports:
      - "8889:8889"
      - "4040-4049:4040-4049"
    tty: true
    stdin_open: true
    volumes:
      - .:/home/ec2-user
